DROP DATABASE IF EXISTS gincana;
CREATE DATABASE gincana;
USE gincana;

CREATE TABLE Dia (
  idDia INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  data DATE NOT NULL UNIQUE
);

CREATE TABLE Turma (
  idTurma INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  turma VARCHAR(70) NOT NULL
);

CREATE TABLE Aluno (
  idAluno INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  nome VARCHAR (77) NOT NULL,
  idade INT(2) NOT NULL,
  idTurma INT,
  CONSTRAINT fkAlunoTurma FOREIGN KEY (idTurma) REFERENCES Turma (idTurma)
);

CREATE TABLE Pontos (
  idPontos INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  pontos INT NOT NULL,
  idAluno INT,
  idDia INT,
  CONSTRAINT fkPontosAluno FOREIGN KEY (idAluno) REFERENCES Aluno (idAluno),
  CONSTRAINT fkPontosDia FOREIGN KEY (idDia) REFERENCES Dia (idDia)
);

INSERT INTO Turma (turma) VALUES ('1° ADM');
INSERT INTO Turma (turma) VALUES ('2° ADM');
INSERT INTO Turma (turma) VALUES ('3° ADM');
INSERT INTO Turma (turma) VALUES ('1° INFO');
INSERT INTO Turma (turma) VALUES ('2° INFO');
INSERT INTO Turma (turma) VALUES ('3° INFO');
INSERT INTO Turma (turma) VALUES ('1° CONT');
INSERT INTO Turma (turma) VALUES ('2° CONT');
INSERT INTO Turma (turma) VALUES ('3° CONT');
INSERT INTO Turma (turma) VALUES ('1° RH');
INSERT INTO Turma (turma) VALUES ('2° RH');
INSERT INTO Turma (turma) VALUES ('3° RH');
